# Generated by Django 2.2.3 on 2019-10-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_Publicacion', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
            ],
        ),
    ]
