# Generated by Django 2.2.3 on 2019-10-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('pregunta', models.TextField()),
                ('respuesta', models.TextField()),
                ('respondida', models.BooleanField()),
            ],
        ),
    ]
