# Generated by Django 2.2.3 on 2019-10-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sol', '0003_auto_20191030_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateTimeField()),
                ('titulo', models.CharField(max_length=30)),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='respondida',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
