# Generated by Django 2.1 on 2019-10-30 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sol', '0004_auto_20191030_0018'),
        ('sol', '0003_auto_20191029_2039'),
    ]

    operations = [
    ]
