# Generated by Django 2.1 on 2019-10-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sol', '0005_merge_20191030_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='respondida',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
