# Generated by Django 2.1 on 2019-11-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sol', '0006_auto_20191030_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='sol/noticias'),
        ),
    ]
