# Generated by Django 2.1 on 2019-11-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sol', '0007_noticia_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
