# Generated by Django 2.1 on 2019-12-03 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sol', '0008_auto_20191117_0247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=30)),
                ('valor', models.IntegerField()),
                ('estudiante', models.IntegerField()),
                ('inicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sol.Inicio')),
            ],
        ),
    ]
