# Generated by Django 2.1 on 2019-12-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sol', '0009_inicio_tarifa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifa',
            name='estudiante',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
