# Generated by Django 2.1 on 2019-12-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sol', '0010_auto_20191203_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifa',
            name='destino',
            field=models.CharField(max_length=60),
        ),
    ]
